Show me the money
edenchazard/garden-of-eden pull request #40
Opened 2024-10-22 17:56 UTC by danblackadder

2024-10-22 18:00 UTC, edenchazard requested changes

2024-10-22 18:27 UTC, danblackadder commented on server/routes/view/[id].ts
> +
I have addressed your changes owner of my life

2024-10-22 19:21 UTC, edenchazard commented
![pout-kiss](https://github.com/user-attachments/assets/e17fa337-cb77-443d-9f68-073e6b8d7ebe)

2024-10-22 20:59 UTC, edenchazard approved these changes

2024-10-23 22:15 UTC, edenchazard commented
closing in favour of #41

2024-10-23 22:15 UTC, closed without merging